/**
 * Autolinking for Linux: the app's dependencies with a linux/ folder (a
 * CMakeLists.txt there) get built into the app and registered with the
 * host.
 *
 * A library's react-native.config.js may name its CMake target and the
 * function that returns its rngtk::Package; both default from the package
 * name (`@acme/react-native-foo` -> acme_react_native_foo and
 * acme_react_native_foo_package):
 *
 *   module.exports = {
 *     dependency: {platforms: {linux: {cmakeTarget: 'foo', packageFunction: 'foo_package'}}},
 *   };
 *
 * run-linux writes autolinking.cmake (adds each linux/ folder to the build,
 * lists the targets) and autolinking.cc (rngtk::autolinkedPackages()) into
 * the app's build directory, and points the app's CMake at them
 * (RNGTK_AUTOLINKING_DIR; rngtk_app() picks them up).
 */
'use strict';

const fs = require('fs');
const path = require('path');

/** A C identifier from a package name. */
function cIdentifier(name) {
  let s = String(name)
    .replace(/^@/, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  if (!s || /^[0-9]/.test(s)) s = `lib_${s}`;
  return s;
}

/** The `linux` part of a dependency's CLI config, or null. */
function dependencyConfig(root, userConfig = {}) {
  const sourceDir = path.resolve(root, (userConfig && userConfig.sourceDir) || 'linux');
  if (!fs.existsSync(path.join(sourceDir, 'CMakeLists.txt'))) return null;
  let packageName = path.basename(root);
  try {
    packageName = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).name || packageName;
  } catch {}
  const base = cIdentifier(packageName);
  return {
    sourceDir,
    packageName,
    cmakeTarget: (userConfig && userConfig.cmakeTarget) || base,
    packageFunction: (userConfig && userConfig.packageFunction) || `${base}_package`,
  };
}

/** The libraries to link, from the CLI config's dependencies. */
function linuxLibraries(dependencies = {}) {
  return Object.values(dependencies)
    .map(d => d && d.platforms && d.platforms.linux)
    .filter(Boolean)
    .sort((a, b) => a.packageName.localeCompare(b.packageName));
}

function cmakePath(p) {
  return p.replace(/\\/g, '/').replace(/"/g, '\\"');
}

/** autolinking.cmake's text. */
function autolinkingCmake(libraries) {
  const lines = [
    '# Generated by `react-native run-linux` (autolinking): the native code of',
    "# the app's dependencies that have a linux/ folder. Don't edit.",
    'set(RNGTK_AUTOLINKED_TARGETS "")',
  ];
  for (const lib of libraries) {
    const binary = `\${CMAKE_BINARY_DIR}/autolinked/${cIdentifier(lib.packageName)}`;
    lines.push(
      `# ${lib.packageName}`,
      `if(NOT TARGET ${lib.cmakeTarget})`,
      `  add_subdirectory("${cmakePath(lib.sourceDir)}" "${binary}")`,
      'endif()',
      `list(APPEND RNGTK_AUTOLINKED_TARGETS ${lib.cmakeTarget})`,
    );
  }
  return `${lines.join('\n')}\n`;
}

/** autolinking.cc's text. */
function autolinkingSource(libraries) {
  const decls = libraries.map(
    lib => `std::shared_ptr<const rngtk::Package> ${lib.packageFunction}();  // ${lib.packageName}`,
  );
  const calls = libraries.map(lib => `      ::${lib.packageFunction}(),`);
  return [
    "// Generated by `react-native run-linux` (autolinking): the packages of the",
    "// app's dependencies that have a linux/ folder. Don't edit.",
    '#include <rngtk/Autolinking.h>',
    '',
    ...decls,
    ...(decls.length ? [''] : []),
    'namespace rngtk {',
    '',
    'PackageList autolinkedPackages() {',
    '  return {',
    ...calls,
    '  };',
    '}',
    '',
    '}  // namespace rngtk',
    '',
  ].join('\n');
}

/**
 * Writes autolinking.cmake and autolinking.cc into `dir` (only when they
 * change, so builds stay incremental). Returns the libraries.
 */
function writeAutolinking(dir, libraries) {
  fs.mkdirSync(dir, {recursive: true});
  const files = {
    'autolinking.cmake': autolinkingCmake(libraries),
    'autolinking.cc': autolinkingSource(libraries),
  };
  for (const [name, text] of Object.entries(files)) {
    const file = path.join(dir, name);
    let old = null;
    try {
      old = fs.readFileSync(file, 'utf8');
    } catch {}
    if (old !== text) fs.writeFileSync(file, text);
  }
  return libraries;
}

module.exports = {
  cIdentifier,
  dependencyConfig,
  linuxLibraries,
  autolinkingCmake,
  autolinkingSource,
  writeAutolinking,
};
