/**
 * package-linux --format rpm: the installed tree under /usr as an RPM,
 * built with rpmbuild from a generated spec. rpm's own dependency
 * generators find what the app links (the host libraries are private to
 * it: not provided, not required), so build it on the distribution it's
 * for (a Fedora container on other systems: see docs/packaging.md).
 */
'use strict';

const fs = require('fs');
const path = require('path');

/** An RPM package name: the app's, lowercase. */
function rpmName(info) {
  if (info.rpm?.name) return info.rpm.name;
  return String(info.name).toLowerCase().replace(/[^a-z0-9+._-]/g, '-');
}

/** RPM versions can't have '-': a pre-release '1.0.0-beta.1' becomes '1.0.0~beta.1'. */
function rpmVersion(version) {
  return String(version).replace(/-/g, '~');
}

function rpmArch() {
  return {arm64: 'aarch64', x64: 'x86_64'}[process.arch] || process.arch;
}

function changelogDate(date) {
  const d = new Date(`${date}T00:00:00Z`);
  const day = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][d.getUTCDay()];
  const month = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'][d.getUTCMonth()];
  return `${day} ${month} ${String(d.getUTCDate()).padStart(2, '0')} ${d.getUTCFullYear()}`;
}

function wrap(text, width = 76) {
  const out = [];
  for (const p of String(text).trim().split(/\n\s*\n/)) {
    let line = '';
    for (const word of p.split(/\s+/)) {
      if (line && line.length + word.length + 1 > width) {
        out.push(line);
        line = word;
      } else {
        line = line ? `${line} ${word}` : word;
      }
    }
    out.push(line, '');
  }
  return out.join('\n').trim();
}

/** The spec. Source0 is a tarball of the tree, relative to /. */
function rpmSpec(info, {maintainer, date, release = 1, source = 'root.tar'}) {
  const name = rpmName(info);
  const lib = info.name.replace(/[.+]/g, '\\$&');
  return `# Generated by react-native package-linux --format rpm.
# The host libraries are the app's own: not provided to other packages, and
# not required from them.
%global __provides_exclude_from ^%{_prefix}/lib/${lib}/.*$
%global __requires_exclude ^(librngtk_host|libhermesvm|libjsi)\\\\.so.*$
# Built already (and stripped of debug info): nothing to extract.
%global debug_package %{nil}

Name:           ${name}
Version:        ${rpmVersion(info.version)}
Release:        ${release}%{?dist}
Summary:        ${info.summary}
License:        ${info.license}
${info.homepage ? `URL:            ${info.homepage}\n` : ''}Source0:        ${source}

%description
${wrap(info.description || info.summary)}

%prep

%build

%install
mkdir -p %{buildroot}
tar -C %{buildroot} -xf %{SOURCE0}

%files
%{_bindir}/${info.name}
%{_prefix}/lib/${info.name}/
%{_datadir}/${info.name}/
%{_datadir}/applications/${info.appId}.desktop
%{_datadir}/metainfo/${info.appId}.metainfo.xml
%{_datadir}/icons/hicolor/*/apps/${info.appId}.*
%license %{_datadir}/licenses/${info.appId}/

%changelog
* ${changelogDate(date)} ${maintainer} - ${rpmVersion(info.version)}-${release}
- Release ${info.version}.
`;
}

/**
 * Builds the RPM from `root` (which has usr/) with rpmbuild in a scratch
 * _topdir. Returns the .rpm's path.
 */
function buildRpm(root, info, {output, run, scratch, maintainer, date}) {
  if (!maintainer) throw new Error('No maintainer for the .rpm: set linux.maintainer ("Name <email>") in app.json');
  const top = path.join(scratch, 'rpmbuild');
  fs.rmSync(top, {recursive: true, force: true});
  for (const d of ['SOURCES', 'SPECS', 'BUILD', 'RPMS', 'SRPMS', 'BUILDROOT']) fs.mkdirSync(path.join(top, d), {recursive: true});
  run('tar', ['--sort=name', '--owner=0', '--group=0', '--numeric-owner', '-cf', path.join(top, 'SOURCES', 'root.tar'), '-C', root, 'usr'], {quiet: true});
  const spec = path.join(top, 'SPECS', `${rpmName(info)}.spec`);
  fs.writeFileSync(spec, rpmSpec(info, {maintainer, date}));
  run('rpmbuild', ['-bb', '--define', `_topdir ${top}`, spec], {quiet: true});
  const arch = rpmArch();
  const dir = path.join(top, 'RPMS', arch);
  const built = fs.readdirSync(dir).find(f => f.endsWith('.rpm'));
  const rpm = path.join(output, built);
  fs.copyFileSync(path.join(dir, built), rpm);
  fs.copyFileSync(spec, path.join(output, path.basename(spec)));
  return {rpm, spec: path.join(output, path.basename(spec)), name: rpmName(info)};
}

module.exports = {rpmName, rpmVersion, rpmSpec, changelogDate, buildRpm};
