import {AppRegistry} from 'react-native';
import App from './App';
import Gallery from './Gallery';
import GalleryAccessibility from './GalleryAccessibility';
import GalleryAppearance from './GalleryAppearance';
import GalleryControls from './GalleryControls';
import GalleryImages from './GalleryImages';
import GalleryKeyboard from './GalleryKeyboard';
import GalleryLists from './GalleryLists';
import GalleryMouse from './GalleryMouse';
import GalleryPlatform from './GalleryPlatform';
import GalleryDialogs from './GalleryDialogs';
import GalleryDragDrop from './GalleryDragDrop';
import GalleryMenus from './GalleryMenus';
import GalleryModal from './GalleryModal';
import GalleryNativeModule from './GalleryNativeModule';
import GalleryNotifications from './GalleryNotifications';
import GallerySelection from './GallerySelection';
import GalleryTitleBar, {GalleryTitleBarChild} from './GalleryTitleBar';
import GalleryWindows, {GalleryWindowChild} from './GalleryWindows';
import Showcase, {ShowcaseWindow} from './Showcase';

AppRegistry.registerComponent('HelloWorld', () => App);
AppRegistry.registerComponent('Gallery', () => Gallery);
AppRegistry.registerComponent('GalleryLists', () => GalleryLists);
AppRegistry.registerComponent('GalleryImages', () => GalleryImages);
AppRegistry.registerComponent('GalleryControls', () => GalleryControls);
AppRegistry.registerComponent('GalleryAppearance', () => GalleryAppearance);
AppRegistry.registerComponent('GallerySelection', () => GallerySelection);
AppRegistry.registerComponent('GalleryKeyboard', () => GalleryKeyboard);
AppRegistry.registerComponent('GalleryMouse', () => GalleryMouse);
AppRegistry.registerComponent('GalleryAccessibility', () => GalleryAccessibility);
AppRegistry.registerComponent('GalleryPlatform', () => GalleryPlatform);
AppRegistry.registerComponent('GalleryModal', () => GalleryModal);
AppRegistry.registerComponent('GalleryDialogs', () => GalleryDialogs);
AppRegistry.registerComponent('GalleryMenus', () => GalleryMenus);
AppRegistry.registerComponent('GalleryDragDrop', () => GalleryDragDrop);
AppRegistry.registerComponent('GalleryNotifications', () => GalleryNotifications);
AppRegistry.registerComponent('GalleryNativeModule', () => GalleryNativeModule);
AppRegistry.registerComponent('GalleryWindows', () => GalleryWindows);
AppRegistry.registerComponent('GalleryWindowChild', () => GalleryWindowChild);
AppRegistry.registerComponent('GalleryTitleBar', () => GalleryTitleBar);
AppRegistry.registerComponent('GalleryTitleBarChild', () => GalleryTitleBarChild);
AppRegistry.registerComponent('Showcase', () => Showcase);
AppRegistry.registerComponent('ShowcaseWindow', () => ShowcaseWindow);
